#!/bin/bash
# The even more awesome one-line uninstaller for Amon - Debian based distros 
# Author: Martin Rusev <martin@amon.cx>

# Set variables for the uninstall script
set -e
mongo_install_dir="/usr/local/mongodb"

pip uninstall pymongo amon tornado jinja2

# Stop all daemons 
sudo /etc.init.d/amond stop
sudo /etc/init.d/amon stop
sudo /etc/init.d/mongodb stop

# Cleanup the directories
sudo rm -rf /etc/amon.conf
sudor rm -rf mongo_install_dir


# Remove Amon and mongo from the startup scripts
sudo update-rc.d -f mongodb remove
sudo update-rc.d -f amond remove

echo "*** Amon succesfully removed"
