#!/bin/bash
# The even more awesome one-line uninstaller for Amon - Debian based distros 
# Author: Martin Rusev <martin@amon.cx>

set +e # Don't exit the script if some command fails
delete_mongo=$1 # Inherited from the main script
mongo_install_dir="/usr/local/mongodb"
site_packages=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`
amon_dir="/usr/local/amon"

sudo rm -rf "$site_packages/pymongo*"
sudo rm -rf "$site_packages/amon*"
sudo rm -rf "$site_packages/tornado*"
sudo rm -rf "$site_packages/jinja2"

# Stop and delete the daemons 
if [ -e /etc/init.d/amond ]; then
	sudo /etc/init.d/amond stop
	sudo rm /etc/init.d/amond
fi 

if [ -e /etc/init.d/amon ]; then
	sudo /etc/init.d/amon stop
	sudo rm /etc/init.d/amon
fi 

# Delete the config file
sudo rm /etc/amon.conf

# Remove the directory with the Amon log files
sudo rm -rf "$amon_dir"

# Remove Amon and mongo from the startup scripts
sudo update-rc.d -f amond remove

# Delete Mongo
if [ "$delete_mongo" == 'with-mongo' ]; then
	sudo /etc/init.d/mongodb stop # Stop the daemon
	sudo rm -rf $mongo_install_dir # Delete /usr/local/mongodb
	sudo update-rc.d -f mongodb remove # Remove the process from the startup list
	sudo rm /etc/init.d/mongodb # Delete the configuration file
	sudo rm  /usr/bin/mongo # Delete the mongo executable in /usr/bin
fi 

echo "*** Amon succesfully removed"
