#!/bin/bash
# The even more awesome one-line uninstaller for Amon - Debian based distros 
# Author: Martin Rusev <martin@amon.cx>

set +e # Don't exit the script if some command fails
delete_mongo=$1 # Inherited from the main script
mongo_install_dir="/usr/local/mongodb"
site_packages=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`
amon_dir="/usr/local/amon"

sudo rm -rf "$site_packages/pymongo*"
sudo rm -rf "$site_packages/amon*"
sudo rm -rf "$site_packages/tornado*"
sudo rm -rf "$site_packages/jinja2"

# Stop and delete the daemons 
if [ -e /etc/init.d/amond ]; then
	sudo /etc/init.d/amond stop
	sudo rm /etc/init.d/amond
fi 

if [ -e /etc/init.d/amon ]; then
	sudo /etc/init.d/amon stop
	sudo rm /etc/init.d/amon
fi 

# Delete the config file
sudo rm /etc/amon.conf

# Remove the directory with the Amon log files
if [ -d "$amon_dir" ]; then
	sudo rm -rf "$amon_dir"
fi

# Remove Amon and mongo from the startup scripts
sudo update-rc.d -f amond remove


# Delete Mongo
if [ "$delete_mongo" == 'with-mongo' ]; then

	function is_integer() {
		s=$(echo $1 | tr -d 0-9)
		if [ -z "$s" ]; then
			return 0
		else
			return 1
		fi
	}

	if [ -e /etc/init.d/mongodb ]; then
		sudo /etc/init.d/mongodb stop # Stop the daemon
		sudo rm /etc/mongodb.conf # Delete the configuration file
	fi

	if [ -d "$mongo_install_dir" ]; then
		sudo rm -rf $mongo_install_dir # Delete /usr/local/mongodb
	fi

	sudo update-rc.d -f mongodb remove # Remove the process from the startup list
	
	if [ -e /usr/bin/mongo ]; then
		sudo rm  /usr/bin/mongo # Delete the mongo executable in /usr/bin
	fi

	mongo_pid=$(ps aux | grep mongo | grep -v grep | awk '{print $2}')
	sudo kill -9 $mongo_pid > /dev/null # Kill the mongo process by pid if the /etc method fails
	
	echo "*** MongoDB succesfully removed"
fi 

echo "*** Amon succesfully removed"
