#!/bin/bash
# The even more awesome one-line uninstaller for Amon - Debian based distros 
# Author: Martin Rusev <martin@amon.cx>

# Set variables for the uninstall script
set -e
$delete_mongo=$1
mongo_install_dir="/usr/local/mongodb"
amon_install_dir="/usr/local/amon"


command_exists() {
    type "$1" &> /dev/null ;
}


pip uninstall pymongo amon tornado jinja2



sudo rm -rf /etc/amon.conf
sudo rm -rf $amon_install_dir

# Remove Amon from the launch list
launchctl unload -w ~/Library/LaunchAgents/org.amon.amond.plist
sudo rm -rf ~/Library/LaunchAgents/org.amon.amond.plist

# Delete Mongo
if [ $delete_mongo == y ]; then
	if command_exists brew ; then
		brew uninstall mongodb
	elif command_exists port ; then
		sudo port uninstall mongodb
	fi
fi 

echo "*** Amon succesfully removed"
