#!/bin/bash
# The even more awesome one-line uninstaller for Amon - RPM based distros 
# Author: Martin Rusev <martin@amon.cx>
# Don't exit the script if some command fails
set +e
delete_mongo=$1 # Inherited from the main script
mongo_install_dir="/usr/local/mongodb"
amon_dir="/usr/local/amon"

site_packages=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`

sudo rm -rf "$site_packages/pymongo*"
sudo rm -rf "$site_packages/amon*"
sudo rm -rf "$site_packages/torando*"
sudo rm -rf "$site_packages/jinja2"

# Stop and delete the daemons 
if [ -e /etc/init.d/amond ]; then
	sudo /etc/init.d/amond stop
	sudo rm /etc/init.d/amond
fi 

if [ -e /etc/init.d/amon ]; then
	sudo /etc/init.d/amon stop
	sudo rm /etc/init.d/amon
fi 

sudo rm /etc/amon.conf

# Remove the directory with the Amon log files
sudo rm -rf "$amon_dir" # Delete /usr/local/amon

# Remove Amon and mongo from the startup scripts
chkconfig --del amond

# Delete Mongo
if [ $delete_mongo == 'with-mongo' ]; then
	sudo /etc/init.d/mongodb stop #Stop the daemon
	sudo rm -rf $mongo_install_dir # Delete /usr/local/mongodb
	sudo rm /etc/init.d/mongodb # Remove the process from the startup list
	chkconfig --del mongodb 
	sudo rm /usr/bin/mongo
fi 


echo "*** Amon succesfully uninstalled"
