#!/bin/bash
# The awesome one-liner for Amon
# Author: Martin Rusev <martin@amon.cx>

command_exists() {
    type "$1" &> /dev/null ;
}

set -e 
delete_mongo=$1
echo $delete_mongo

if [ "$delete_mongo" == 'with-mongo' ]; then
	echo 'test me'
fi

# Debian based distros - Tested and supported on : Debian, Ubuntu
if command_exists dpkg ; then
	curl http://uninstall.amon.cx/debian -O debian_uninstaller
	sudo bash debian_uninstaller $delete_mongo
	rm -rf debian_uninstaller*
# RPM based distros - Tested and supported on : Fedora, CentOS
elif command_exists rpm ; then
	curl https://raw.github.com/martinrusev/amon/master/uninstallers/rpm_uninstaller -O
	sudo bash rpm_uninstaller $delete_mongo
	rm -rf rpm_uninstaller*
# Mac OS
elif [ "$(uname -s)" != "Darwin" ]; then
	curl ttps://raw.github.com/martinrusev/amon/master/uninstallers/macos_uninstaller -O
	sudo bash macos_uninstaller $delete_mongo
	rm -rf macos_uninstaller*
else 
	echo "Your operating system is not supported at the moment"
fi
