#!/bin/bash
# The awesome one-liner for Amon
# Author: Martin Rusev <martin@amon.cx>

command_exists() {
    type "$1" &> /dev/null ;
}

set -e 

echo "Do you want to keep MongoDB? (y/n)"
read delete_mongo

if [[ $delete_mongo == "Y" || $delete_mongo == "y"  ]]; then
	echo "Amon will delete your MongoDB installation"
else
	echo "Amon will leave your MongoDB as it is"
fi

# Debian based distros - Tested and supported on : Debian, Ubuntu
if command_exists dpkg ; then
	curl https://raw.github.com/martinrusev/amon/master/uninstallers/debian_uninstaller -O
	sudo bash debian_uninstaller $delete_mongo
	rm -rf debian_uninstaller*
# RPM based distros - Tested and supported on : Fedora, CentOS
elif command_exists rpm ; then
	curl https://raw.github.com/martinrusev/amon/master/uninstallers/rpm_uninstaller -O
	sudo bash rpm_uninstaller $delete_mongo
	rm -rf rpm_uninstaller*
# Mac OS
elif [ "$(uname -s)" != "Darwin" ]; then
	curl ttps://raw.github.com/martinrusev/amon/master/uninstallers/macos_uninstaller -O
	sudo bash macos_uninstaller $delete_mongo
	rm -rf macos_uninstaller*
else 
	echo "Your operating system is not supported at the moment"
fi
