#!/bin/bash
# The one-line uninstaller for Amon
# Author: Martin Rusev <martin@amon.cx>

command_exists() {
    type "$1" &> /dev/null ;
}

file_exists() {
	[ -f "$1" ]
}

set +e # Don't exit the script if some command fails
DISTRO= 
# Debian based distros - Tested and supported on : Debian, Ubuntu
if file_exists /etc/debian_version ; then
    DISTRO='debian'
elif file_exists /etc/system-release; then
    DISTRO='rpm'
fi

site_packages=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`
amon_log_dir="/var/log/amon"

sudo rm -rf "$site_packages/pymongo*"
sudo rm -rf "$site_packages/amon*"
sudo rm -rf "$site_packages/tornado*"
sudo rm -rf "$site_packages/jinja2"

# Stop and delete the daemon 
if [ -e /etc/init.d/amon ]; then
	sudo /etc/init.d/amon stop
	sudo rm /etc/init.d/amon
fi 

# Delete the config file
sudo rm /etc/amon.conf

# Remove the directory with the Amon log files
if [ -d "$amon_log_dir" ]; then
	sudo rm -rf "$amon_log_dir"
fi

echo "*** Amon succesfully removed"
