#! /bin/bash

### BEGIN INIT INFO
# Provides:          mongodb
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the mongodb server
# Description:       starts mongodb 
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/mongodb/bin/mongod
DAEMON_OPTS="--config /etc/mongodb.conf"
PIDFILE=/usr/local/mongodb/mongodb.pid
NAME=mongodb
DESC=mongodb

test -x $DAEMON || exit 0

#set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS --start -- run
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --quiet --pidfile $PIFDILE --exec $DAEMON --stop
        echo "$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --quiet --pidfile $PIDFILE --exec $DAEMON --stop
        sleep 1
        start-stop-daemon --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS --start -- run
        echo "$NAME."
        ;;
  reload)
      echo -n "Reloading $DESC configuration: "
      start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE --exec $DAEMON
      echo "$NAME."
      ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
