#!/bin/bash
# The awesome one-liner for Amon
# Author: Martin Rusev <martin@amon.cx>

command_exists() {
    type "$1" &> /dev/null ;
}

set -e 

# Debian based distros - Tested and supported on : Debian, Ubuntu
if command_exists dpkg ; then
	wget --no-check-certificate https://raw.github.com/martinrusev/amon/master/installers/debian 
	sudo bash debian
	rm -rf debian
# RPM based distros - Tested and supported on : Fedora, CentOS
elif command_exists rpm ; then
	wget --no-check-certificate https://raw.github.com/martinrusev/amon/master/installers/rpm_based
	sudo bash rpm_based
	rm -rf rpm_based
# Mac OS
elif [ "$(uname -s)" != "Darwin" ]; then
	wget --no-check-certificate https://raw.github.com/martinrusev/amon/master/installers/macos
	sudo bash macos
	rm -rf macos
else 
	echo "Your operating system is not supported at the moment"
fi
