#!/bin/bash
# The awesome one-liner for Amon - Mac OS 
# Author: Martin Rusev <martin@amon.cx>

command_exists() {
    type "$1" &> /dev/null ;
}

file_exists() {
	[ -f "$1" ]
}


# Set variables for the installation
set -e
mongo_check=$(ps aux | grep -c mongo)
version=$1 # Inherited from the main script
amon_install_dir="/usr/local/amon"

echo "***  Installing Amon $version ..."

# Install easy_install if necessary
	if ! command_exists easy_install ; then
		curl "http://peak.telecommunity.com/dist/ez_setup.py" 
		sudo python ez_setup.py
		rm -rf ez_setup.py
	fi

# Install Amon

	# Cleanup the directory from old amon installations
	rm -rf amon
    curl "http://install.amon.cx/amon-$version.zip" 
	tar -xf "amon-$version.zip"
	
	cd "amon"

	sudo python setup.py install 
	
	python generate_config.py
	
	# Copy the generated configuration file from the current directory
	# If Amon was previously installed, the generator will just a secret_key
	sudo cp amon.conf /etc/amon.conf
	
	
	# Create a directory for the daemons
	sudo mkdir -p "$amon_install_dir"

	# Copy the daemons
	sudo cp contrib/amon/amon "$amon_install_dir"/amon
	sudo cp contrib/amon/amond "$amon_install_dir"/amond
	


	mkdir -p ~/Library/LaunchAgents
    cp contrib/amon/macos/org.amon.amond.plist ~/Library/LaunchAgents/
    launchctl unload ~/Library/LaunchAgents/org.amon.amond.plist
    launchctl load -w ~/Library/LaunchAgents/org.amon.amond.plist


# Install MongoDB - use homebrew or ports

	if ! command_exists mongo ; then
		if command_exists brew ; then
			brew install mongodb
		elif command_exists port ; then
			sudo port install mongodb
		fi
	fi

# Show a message about where to go for help.

	print_troubleshooting_instructions() {
		echo
		echo "For troubleshooting instructions, please see the Amon User Guide :"
		echo "http://amon.cx/guide/"
		echo
		echo "To uninstall Amon, \`curl uninstall.amon.cx | sh\`"
	}


# All done!
  
  # If the collector daemon is running - restart it 
  if  [ "ps aux | grep org.amon.amond" ]; then
	  echo "*** Amon succesfully updated"
	  launchctl stop org.amon.amond
	  launchctl start org.amon.amond
  else
	  echo "*** Amon succesfully installed"
	  echo "*** The web application is not running by default, you can start with \`/usr/local/amon/amon start\`"
  fi

  # If the web application is running - restart it 
  if  [ "ps aux | grep amon" ]; then
	  sudo /usr/local/amon/amon restart
  fi


  # Cleanup the directory
  rm -rf amon # Delete the directory with the Amon install files
  rm amon-$version.zip # Delete the archive
  
  print_troubleshooting_instructions

