#!/bin/bash
# The awesome one-liner for Amon - Mac OS 
# Author: Martin Rusev <martin@amon.cx>

command_exists() {
    type "$1" &> /dev/null ;
}

file_exists() {
	[ -f "$1" ]
}


# Set variables for the installation
set -e
mongo_install_dir="/usr/local/mongodb"
mongo_extract_dir="mongodb-linux-i686-2.0.0"
mongo_check=$(ps aux | grep -c mongo)
version=$1 # Inherited from the main script
bash_script_dir="$( cd "$( dirname "$0" )" && pwd )"
amon_install_dir="/usr/local/amon"

echo "***  Installing Amon $version ..."

# Install easy_install if necessary
	if ! command_exists easy_install ; then
		curl "http://peak.telecommunity.com/dist/ez_setup.py" 
		sudo python ez_setup.py
		rm -rf ez_setup.py
	fi

# Install Amon

	# Cleanup the directory from old amon installations
	sudo rm -rf amon-*
	curl "https://s3-eu-west-1.amazonaws.com/amon/amon-$version.tar.gz" -O
	tar -zxvf "amon-$version.tar.gz" > /dev/null
	cd "amon-$version"


	#sudo python setup.py install
	cd "$bash_script_dir"
	
	# Copy the configuration file. Don't overwrite configurartion files
	if ! file_exists "/etc/amon.conf" ; then
		sudo cp amon-$version/config/amon.conf /etc/amon.conf
	fi

	
	# Create a directory for the daemons
	sudo mkdir -p "/usr/local/amon"

	# Copy the daemons
	sudo cp amon-$version/contrib/amon/amon "$amon_install_dir"/amon
	sudo cp amon-$version/contrib/amon/amond "$amon_install_dir"/amond
	


	mkdir -p ~/Library/LaunchAgents
    sudo cp amon-$version/contrib/amon/macos/org.amon.amond.plist ~/Library/LaunchAgents/
    launchctl load -w ~/Library/LaunchAgents/org.amon.amond.plist


# Install MongoDB - use homebrew or ports

	if ! command_exists mongo ; then
		if command_exists brew ; then
			brew install mongodb
		elif command_exists port ; then
			sudo port install mongodb
		fi
	fi

# Show a message about where to go for help.

	print_troubleshooting_instructions() {
		echo
		echo "For troubleshooting instructions, please see the Amon User Guide :"
		echo "http://amon.cx/guide/"
		echo
		echo "To uninstall Amon, \`curl uninstall.amon.cx | sh\`"
	}


# All done!
  
  # If the collector daemon is running - restart it 
  if  [ "ps aux | grep org.amon.amond" ]; then
	  echo "*** Amon succesfully updated"
	  sudo launchctl stop org.amon.amond
	  sudo launchctl start org.amon.amond
  else
	  echo "*** Amon succesfully installed"
	  echo "*** The web application is not running by default, you can start with \`/usr/local/amon/amon start\`"
  fi

  # If the web application is running - restart it 
  if  [ "ps aux | grep amon" ]; then
	  sudo /usr/local/amon/amon restart
  fi


  # Cleanup the directory
  sudo rm -rf amon-*
  print_troubleshooting_instructions

