#!/usr/bin/python
import subprocess

# Kill the amon_start process and don't print the subprocess message
subprocess.Popen(['killall', '-v','amon_start'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True)
print "Amon stopped"

