#!/usr/bin/python
### BEGIN INIT INFO
# Provides:          amond
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the Amon web interface
# Description:       Runs the amon web application.
### END INIT INFO
import logging
import sys

try:
	import amon
except:
	print 'Amon is not installed'
	sys.exit()

from amon.system.daemon import Daemon
from amon.web.server import application
from amon.core import settings
import tornado.ioloop

PIDFILE = '/var/run/amon.pid'
LOGFILE = '/var/log/amon.log'

# Configure logging
logging.basicConfig(filename=LOGFILE,level=logging.DEBUG)

class AmonWebDaemon(Daemon):
	
	def run(self):
		application.listen(int(settings.WEB_APP['port']))
		tornado.ioloop.IOLoop.instance().start()
		
if __name__ == "__main__":

	daemon = AmonWebDaemon(PIDFILE)
	
	if len(sys.argv) == 2:
		if 'start' == sys.argv[1]:
			try:
				daemon.start()
			except:
				pass
		elif 'stop' == sys.argv[1]:
			print "Stopping the Amon web application ..."
			daemon.stop()
		elif 'restart' == sys.argv[1]:
			print "Restaring the Amon web application ..."
			daemon.restart()
		elif 'status' == sys.argv[1]:
			try:
				pf = file(PIDFILE,'r')
				pid = int(pf.read().strip())
				pf.close()
			except IOError:
				pid = None
			except SystemExit:
				pid = None

			if pid:
				print 'The Amon web app is running as pid %s' % pid
				print 'You can check it out at {0}:{1}'.format(settings.WEB_APP['host'],
						settings.WEB_APP['port'])
			else:
				print 'The Amon web application is not running.'
		
		else:
			print "Unknown command"
			sys.exit(2)
			sys.exit(0)
	else:
		print "usage: %s start|stop|restart|status" % sys.argv[0]
		sys.exit(2)

