#!/usr/bin/python
import sys
import logging
import cherrypy
from amon.web.server import root, config

try:
	import amon
except:
	print 'Amon is not installed'
	sys.exit()

from amon.system.daemon import Daemon

PIDFILE = '/var/run/amon.pid'
LOGFILE = '/var/log/amon.log'

# Configure logging
logging.basicConfig(filename=LOGFILE,level=logging.DEBUG)

class AmonWebDaemon(Daemon):
	
	def run(self):

		cherrypy.config.update({
			'server.socket_host': '127.0.0.1',
			'server.socket_port': 2464,
			'engine.autoreload_on': False	
			})

		while True:
			cherrypy.tree.mount(root, "/", config)
		
if __name__ == "__main__":

	daemon = AmonWebDaemon(PIDFILE)
	
	if len(sys.argv) == 2:
		if 'start' == sys.argv[1]:
			try:
				daemon.start()
			except:
				pass
		elif 'stop' == sys.argv[1]:
			print "Stopping the Amon web interface ..."
			daemon.stop()
		elif 'restart' == sys.argv[1]:
			print "Restaring the Amon web interface ..."
			daemon.restart()
		elif 'status' == sys.argv[1]:
			try:
				pf = file(PIDFILE,'r')
				pid = int(pf.read().strip())
				pf.close()
			except IOError:
				pid = None
			except SystemExit:
				pid = None

			if pid:
				print 'The Amon web interface is running as pid %s and you can check it out at http://127.0.0.1:2464' % pid
			else:
				print 'The Amon web interface is not running.'
		
		else:
			print "Unknown command"
			sys.exit(2)
			sys.exit(0)
	else:
		print "usage: %s start|stop|restart|status" % sys.argv[0]
		sys.exit(2)

